### ISSUE TITLE
Bug when deleting an item and then adding a new one

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#103]
![screen shot 2016-04-13 at 12 21 10](https://cloud.githubusercontent.com/assets/548708/14490312/6a3591dc-0172-11e6-99e1-e49a75acbcb0.png)

The form gets validated on start, and the description from the deleted item is still present above the label.

**Comment by Markionium** [comment]
d2-ui `<FormBuilder />` component needs to not run the validators when the page is cleared..

**Comment by Markionium** [comment]
No longer seems to happen on demo.
