### ISSUE TITLE
Data dimension automatically checked for new org.unit group sets

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#104]
If I save a new org.unit group set without checking "Data dimension", it is checked if I edit the same item. 

![screen shot 2016-04-13 at 14 41 27](https://cloud.githubusercontent.com/assets/548708/14493524/292154e2-0186-11e6-8062-95784a47197c.png)
![screen shot 2016-04-13 at 14 41 43](https://cloud.githubusercontent.com/assets/548708/14493529/2db3d0b6-0186-11e6-8442-c038707fc883.png)

**Comment by turban** [comment]
Related: If edit a group set and uncheck "Compulsary", I'm not allowed to save the changes. 

![screen shot 2016-04-13 at 14 51 04](https://cloud.githubusercontent.com/assets/548708/14493788/b089c58a-0187-11e6-960a-e25579a368b2.png)

**Comment by turban** [comment]
Data dimension is also automatically selected for new categories: 

![screen shot 2016-04-14 at 11 53 28](https://cloud.githubusercontent.com/assets/548708/14524213/9f89d97c-0237-11e6-9adc-5fe3c8f3b24e.png)

**Comment by turban** [comment]
+ Category Option Group Set

**Comment by Markionium** [comment]
The API seems to automatically set the `dataDimension` property to true when no value is passed on POST

**Comment by Markionium** [comment]
It is set to true  by default because in most cases this is the desired behavior. The UI will need to reflect this by automatically checking the box in the form when creating a new object that `dataDimension` as a property.
