### ISSUE TITLE
Not possible to add new org.unit levels

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#105]
There is no add button. 

![screen shot 2016-04-13 at 14 56 16](https://cloud.githubusercontent.com/assets/548708/14493828/f11e6966-0187-11e6-8553-371526799b90.png)

**Comment by Markionium** [comment]
Thats correct, those are generated and so it not be should not be possible to add them.

**Comment by Markionium** [comment]
This will be replaced with the new OU Level UI component.
