### ISSUE TITLE
Not allowed to delete new data element category

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#110]
500 Server Error

![screen shot 2016-04-14 at 12 08 57](https://cloud.githubusercontent.com/assets/548708/14524700/f098bb74-0239-11e6-900c-d612d2c9a77e.png)

**Comment by turban** [comment]
The reason was that the category was connected to a category option combination. When I deleted the combination, I could also delete the category.

**Comment by Markionium** [comment]
I believe that is correct behaviour or would you expect something else? Perhaps a better error message.

**Comment by turban** [comment]
I would expect an error message explaining why it could not be deleted, but I guess it's not a big issue.

**Comment by Markionium** [comment]
This is indeed happening due to the 500 server error that returns a stack trace instead of a message. If the response has a `message` property that would be displayed instead.

Will create a issue on launchpad for the api error.
