### ISSUE TITLE
Annualized checkbox can not be toggled for indicators

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#113]
If I check the annualized checkbox, it can not be unchecked as the save button is disabled. 

<img width="180" alt="screen shot 2016-04-14 at 21 30 23" src="https://cloud.githubusercontent.com/assets/548708/14541065/5dc570cc-0288-11e6-9416-1e95c2873c26.png">

**Comment by Markionium** [comment]
This is related to the larger issue of required boolean fields. We probably should make sure d2 defaults boolean values to `false` for boolean fields that are required. Additionally we need to make sure that no required validation is run on checkboxes.
