### ISSUE TITLE
"Decimals in data output" is not saved for indicators

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#114]
If I set "Decimals in data output" for an indicator, save it, and then edit it again. My previous choice is not shown in the form (although it could be saved):

<img width="556" alt="screen shot 2016-04-14 at 21 33 01" src="https://cloud.githubusercontent.com/assets/548708/14541161/e00de762-0288-11e6-9088-7bf9039a9060.png">

<img width="561" alt="screen shot 2016-04-14 at 21 36 13" src="https://cloud.githubusercontent.com/assets/548708/14541179/f4450cb0-0288-11e6-87b0-35b9833f64fc.png">

**Comment by Markionium** [comment]
Might be related to #39
