### ISSUE TITLE
Indicator > decimals drop down not set properly

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#117]
In edit indicator screen, the "Decimals in data output" drop down is not set to the appropriate option according to the current value.

- Create a new indicator with decimals = 2.
- Open the edit screen for that indicator.
- Decimals drop down is not set.

![dec1](https://cloud.githubusercontent.com/assets/908206/14567607/28cb6e46-0335-11e6-8b0d-8babf085590c.png)

![dec2](https://cloud.githubusercontent.com/assets/908206/14567608/2c682a8a-0335-11e6-9bf7-c91ea39080e3.png)

**Comment by Markionium** [comment]
Should have been fixed with https://github.com/dhis2/maintenance-app/issues/114 which has not been published yet, but will verify!

**Comment by Markionium** [comment]
Fixed in trunk
