### ISSUE TITLE
Translation of "missing property" messages

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#118]
The user feedback messages for missing properties in add new object forms should use a natural name rather than the data model property name. 

Example: Missing required property "domainType".

Should be: Missing required property: Domain type.

![domain](https://cloud.githubusercontent.com/assets/908206/14637459/a2eb96fc-0631-11e6-978d-906274a9882d.png)

**Comment by Markionium** [comment]
Needs follow up on how to handle these api status messages and i18n workflow.
