### ISSUE TITLE
Trying to create a new object from a card within a tab renders the app unresponsive

### ISSUE THREAD

**Issue by nicolayr** [dhis2/maintenance-app#127]
Reproduce:

1. Click a tab other than "All" at the top of the app
2. Click the "+" button on any card to add any new object

The app becomes unresponsive and has to be reloaded. There's also an error printed to the console.

**Comment by nicolayr** [comment]
Marking as high priority since it completely breaks the app and is quite likely to happen- although it's easy to circumvent. Feel free to change.

**Comment by larshelge** [comment]
Fails with:

babel-polyfill.js:2 Unhandled promise rejection Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.(…)
