### ISSUE TITLE
Support creating associated objects while editing

### ISSUE THREAD

**Issue by nicolayr** [dhis2/maintenance-app#133]
When editing an object that has associations to other objects, it should be possible to create a new instance of the associated object type and add the associated to the initial object.

For example: While editing a data element, open the form to create a new option set. When the new option set has been created, return to the same data element and reload the list of option sets so the newly created one appears in the list. Ideally the newly created option set should automatically be selected as well.

**Comment by Markionium** [comment]
Was not part of 2.24 so moving it to 2.25.

**Comment by jijukjose** [comment]
Document being updated here - https://github.com/dhis2/dhis2-docs/issues/154
