### ISSUE TITLE
Use node to compile SCSS

### ISSUE THREAD

**Issue by nicolayr** [dhis2/maintenance-app#140]
By using [node-sass](https://www.npmjs.com/package/node-sass) (in stead of compass) to compile SCSS into CSS, all app dependencies would be handled by npm.

**Comment by mortenoh** [comment]
Not sure if you use compass, but if not.. postcss + postcss-scss is very
nice.. and opens the posibility for css modules and cssnext (which is
awesome)

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org

**Comment by nicolayr** [comment]
Fixed in 41bc1cdd15b0ec804b69bcecc55a34ba89a1ec00
