### ISSUE TITLE
Not able to build the project for production

### ISSUE THREAD

**Issue by TanvirAtDure** [dhis2/maintenance-app#1420]
development mode build is working but not able to build it for production mode (windows machine), can somebody help me on this issue.
Is there any documentation to understand the application flow?

**Comment by varl** [comment]
Hi @TanvirAtDure :wave: 

Generally we do not test on Windows, so I don't know why the build doesn't work there.

If you need the latest build from `master`, it is available here: https://github.com/d2-ci/maintenance-app/archive/master.zip

There is user documentation available here: https://docs.dhis2.org/master/en/user/html/dhis2_user_manual_en_full.html#about_maintenance_app

Or do you mean flow in terms of the code in the app? We don't have that I'm afraid.
