### ISSUE TITLE
Main tabs (data elements, indicators, orgunits) are clipped

### ISSUE THREAD

**Issue by olavpo** [dhis2/maintenance-app#149]
Unless you have a big screen, the tab titles are clipped - even though there's a lot of available space. I image there might be other languages where this might be even more visible.

<img width="1020" alt="skjermbilde 2016-05-10 kl 15 56 09" src="https://cloud.githubusercontent.com/assets/16152555/15149075/71810e60-16c8-11e6-8d4c-575337440d69.png">

**Comment by larshelge** [comment]
Which browser is this? Could you double-check? I cannot reproduce, it might be fixed already.

**Comment by olavpo** [comment]
Looks like it was in Safari. I actually though it was Chrome, otherwise I might not have bothered reporting. Chrome left, Safari right in screenshot:

<img width="904" alt="screenshot" src="https://cloud.githubusercontent.com/assets/16152555/15849255/e6b7613c-2c91-11e6-93d6-ccc7f281e2ba.png">
