### ISSUE TITLE
Facility layer icons not appearing on the org unit group edit interface

### ISSUE THREAD

**Issue by velasvalen17** [dhis2/maintenance-app#154]
Icons used on the Facility layer on GIS app are not loading correctly on the org unit maintenance app where they are supposed to be defined.

This issue appears on demo/dev servers and on local instances (ver 2.23 build 22882).

Screen attached showing the issue.
![seleccion_084](https://cloud.githubusercontent.com/assets/7974371/15289521/064be340-1b73-11e6-80e8-8effc6d933da.png)

**Comment by larshelge** [comment]
Appears that images have an absolute path (assuming the server context is root /) instead of relative.

**Comment by Markionium** [comment]
Possibly a regression issue due to updated config.

**Comment by Markionium** [comment]
This was fixed.
