### ISSUE TITLE
Select by org unit level and org unit group in tree

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#155]
For the organisation unit tree, add support for selecting organisation units by level and by group.

Add selectors for org unit levels and for org unit groups. Add buttons for "Select in group", "Unselect group", "Select by level", "Unselect level".

![select](https://cloud.githubusercontent.com/assets/908206/15289747/7c0c3386-1b74-11e6-8841-747a4115d574.png)

**Comment by nicolayr** [comment]
https://github.com/dhis2/maintenance-app/commit/8dd4fe685ae795dc6e6da8bbda44cb4cbdc284bc
