### ISSUE TITLE
Organisation Unit Group set: Error message not related to properties in form

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/maintenance-app#156]
I tried to create a new organisation unit group set. I filled out all the parameters. When I clicked save, I got an error message saying that I'm "missing required property 'id'". However, there's no field in the form that is called "id".  
Could you investigate why I get the error message? All fields are filled out.
Also, could you change the error message so that it's clear which field that is filled out the wrong way?

![orgunitgroupset_errormessage-kopi](https://cloud.githubusercontent.com/assets/18207911/15361193/db9243a2-1d10-11e6-97ac-b223b38a4923.png)

**Comment by Markionium** [comment]
Reported as a launchpad bug here https://bugs.launchpad.net/dhis2/+bug/1583507

**Comment by mortenoh** [comment]
This is probably an unintended consequence of commit 23036. Not sure what
the best fix is, it will require some time (will try to fix it tomorrow).

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org

**Comment by mortenoh** [comment]
Fixed in trunk now

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org
