### ISSUE TITLE
Creating DE with tracker domain type fails with "missing property aggregationType"

### ISSUE THREAD

**Issue by grelland** [dhis2/maintenance-app#157]
Creating a new DE with Domain Type 'Tracker' seems to do the right thing, that is: disabling 'aggregation operator' and selecting 'None'.

Saving the DE, however, returns a snackbar message displaying 'Missing required property "aggregationType".'

Currently, switching to Aggregate, setting the aggregation type to 'None' and switching back to Tracker is a viable workaround.

**Comment by Markionium** [comment]
Fixed!
