### ISSUE TITLE
Suggestion: Replace "Share" with "Sharing settings" (or similar)

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/maintenance-app#158]
In the action menu, the user can select the option "Share". However, this option opens a dialog box called "Sharing settings". I suggest that the name in the menu is changed to "Sharing settings" or similar to make it clear to the user that this function doesn’t' let him/her share anything, he/she can just change the settings. 

Compare also with the analysis apps how "Share" is used there. The functionality of "Share" should be similar throughout the different apps.

**Comment by Markionium** [comment]
@ceciliapersson Please update this accordingly in the user documentation :)
