### ISSUE TITLE
Question: Translate options in dialog box not consistent

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/maintenance-app#159]
The translate dialog box differ from data type to data type within the Maintenance app. Most of the times, the translate dialog box has three options: Name, Short name and Description.

However, the dialog box options are different for some data types, for exemple:
- Indicator Type and Indicator Group have two options: Name and Short name. 
- Data element has four options: Name, Short name, Description and Form name.

Do the differences depend on the data type? Or could the translate dialog box made to be consistent for all data types?

![translate_indictorgroupset](https://cloud.githubusercontent.com/assets/18207911/15462984/a667f140-20c6-11e6-936d-7ba73592a5fd.png)
![translate_indictortype](https://cloud.githubusercontent.com/assets/18207911/15462983/a6676b8a-20c6-11e6-806a-8272a8cbc656.png)
![translate_indictorgroup](https://cloud.githubusercontent.com/assets/18207911/15462985/a66857e8-20c6-11e6-8212-be6fd46de8d0.png)
![translate_dataelement](https://cloud.githubusercontent.com/assets/18207911/15463244/4b383ee0-20c8-11e6-81f8-75e764bea328.png)

**Comment by Markionium** [comment]
`https://play.dhis2.org/dev/api/schemas/dataElement.json` we now have a root property called `translatable`, we also have `translationKey` for properties that can be translated. That should be generic enough to extend later, so what the d2js lib should do then… is to check for  `translatable=true` and then loop through the `properties` array and get all where `_.isDefined(translationKey)` (edited)

**Comment by ceciliapersson** [comment]
So the Translate form will be different from metadata object to metadata object depending on which properties are marked as "translate"?

**Comment by Markionium** [comment]
Yes correct, but it shouldn't change much compared to how it is currently ;)
