### ISSUE TITLE
Org units: Add long and lat fields in Create and Edit forms

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/maintenance-app#163]
Add coordinates fields in the Create and Edit forms for organisation units.

**Comment by Markionium** [comment]
Implemented in 2.24

**Comment by Markionium** [comment]
Backport to 2.23 when possible.

**Comment by ceciliapersson** [comment]
Long lat fields documented:
https://ci.dhis2.org/docs/master/en/user/html/manage_org_unit.html#create_org_unit
