### ISSUE TITLE
Indicator numerator element labels are flowing into each other

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#172]
In the indicator numerator/denominator screens, the labels for data elements, programs, organisation unit groups and constants will flow into each other for resolutions around 1300 (which we support).

Suggested fixes:
- Shorten Organisation unit groups to "Org unit groups".
- Use almost full width of the screen for the numerator dialog (no need to keep a lot of empty space left and right of it on small screens - this is good in any case when you have long names in the selection).

![indi](https://cloud.githubusercontent.com/assets/908206/15842571/2aef7c3c-2c28-11e6-92f6-f504a28d2fd2.png)

**Comment by jason-p-pickering** [comment]
@larshelge , part of the challenge here is using abbreviations for things like "OrgUnits". It may work in English, but may not work in other languages, as it may or may not be possible to abbreviate this to only 8 characters. For instance, "Organisation enheter" (or worse Organisatoriska enheter)  is not readily abbreviated, maybe to "OrgEnhet", but I think you see what I am getting at. Whatever the solution, considering real estate space beyond English should probably be a consideration. 

The other point about using abbreviations here is that they may complicate the translation. Obviously "OrgUnit" is kind of a fundemental thing, which translators will need to try and come up for an abbreviation for, but if we must shorten these things, then I think we need to indicate how many characters constitute an acceptable number before they will encounter problems with the layout.
