### ISSUE TITLE
Empty strings (uniqueness)

### ISSUE THREAD

**Issue by Markionium** [dhis2/maintenance-app#176]
When a value is set to empty string (by removing the value or tabbing into the field) those empty values are send to the server. 

Which might not allow to save the object as empty values are also considered unique.

To resolve this from the client side we should not send empty strings. (Might want to solve this in d2 before saving the values, but this might need some more thought)

**Comment by Awnage** [comment]
I encountered this as well with a couple models.

Example route: `/dhis-web-maintenance/#/edit/dataElementSection/dataElementGroup/add`

**How to replicate**:

1. Add new Data Element Group
2. Specify a unique Name
3. Put a space (possibly anything) into the shortname field, but then remove it
4. Save
5. Add a second new DE Group
6. Specify a unique Name
7. Put a space into the shortname, then remove it
8. Put something into the code field (so the form thinks we are entering data)
9. Save
10. Check network console for error 500 response. Digging through you will see:
  ```
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint &quot;uk_6x37lph70r5mh15a71pf1tj17&quot;
    Detail: Key (shortname)=() already exists.
```

**Expectation**:
Either allow for empty shortnames, or prevent submission.

**Comment by larshelge** [comment]
Empty strings will be trimmed to null on the API side in trunk now.

**Comment by nicolayr** [comment]
Does that mean this issue has been resolved? @larshelge @Markionium

**Comment by Markionium** [comment]
@nicolayr Probably, but we should verify before closing this.
