### ISSUE TITLE
Value type of option set must be mandatory

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#189]
The value type of option set must be made mandatory / not-null. When set to null, it causes problems when entering attributes and attribute values at a later stage.

**Comment by Markionium** [comment]
@larshelge It's not mandatory in the model. ;) We can override it in the app but it should probably be fixed in the model.

**Comment by larshelge** [comment]
OptionSet.valueType made mandatory in the model now. This triggers value type validation in the UI.
