### ISSUE TITLE
Custom attribute issues

### ISSUE THREAD

**Issue by Markionium** [dhis2/maintenance-app#208]
- [ ] "I guess you need to send in null, and not false for yes-only attributes, we should probably fix on the backend also"
- [ ] The objects that attributes could be linked to can be dynamic based on the keys on the attribute object
- [ ] Attributes support a sortOrder which can be used to sort attributes on the edit/add fields.
- [ ] The list of objects that options can be added to can be generated as a dynamic list from the attribute object, this will make the solution more generic for when attributes are added to other objects than the currently supported list.

**Comment by abyot** [comment]
Custom attribute of value type Yes/No or Yes Only renders properly for option sets. However, trying to select behaves strangely. It returns back to sort of option edit page...

![image](https://cloud.githubusercontent.com/assets/4967749/20324416/cdd140ca-ab80-11e6-93c5-7142a66b023f.png)

**Comment by Markionium** [comment]
@abyot this is more an issue related to optionSet management rather custom attributes. I'll create a separate issue for this
