### ISSUE TITLE
Indicator numerator: Rename to org unit counts

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#213]
In the indicator numerator screen, rename "Organisation unit counts" to "Org unit counts". This to save real estate as the header is getting crammed.

![org](https://cloud.githubusercontent.com/assets/908206/17444130/a9f4b476-5b3e-11e6-819b-435ae0b87d94.png)

**Comment by jason-p-pickering** [comment]
Not really useful solution, as it may not be applicable to all languages.

**Comment by Markionium** [comment]
This is a duplicate of https://github.com/dhis2/maintenance-app/issues/172
