### ISSUE TITLE
2.24 top menu: validation rule and group available in top menu

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#219]
In version 2.24, "validation rule" and "validation rule group" are available for search in the top menu. This UI is not yet completed which can be confusing to users. We should temporarily disable these until they are ready.

**Comment by Markionium** [comment]
Fixed in https://github.com/dhis2/d2-ui/commit/0df0c97542dd6c09a5840219c17dab2c3532f57a

**Comment by Markionium** [comment]
This will mean apps need to be updated with the new menu.
