### ISSUE TITLE
Configurable columns for list

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#223]
Make the columns to display in object lists configurable. Currently the app displays name, public access and last updated properties. 

It should be possible to select among the following properties.
## Properties
- Name (selected by default)
- Short name (where applicable)
- Code
- UID
- Public access (selected by default)
- Last updated (selected by default)
- Created
- Owner (user)

**Comment by Markionium** [comment]
Related to https://github.com/dhis2/d2-ui/issues/23 but will leave this open as it has a better description.
