### ISSUE TITLE
18n issues

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/maintenance-app#225]
Unit: https://translate.dhis2.org/en/maintenance-app/translate/src/i18n/en.po#unit=756489
Source: Id
Current translation:
Your question or comment:
I bet this should be "ID", unless you are discussing the ego and super-ego as well.

Unit: https://translate.dhis2.org/en/maintenance-app/translate/src/i18n/en.po#unit=756538
Source: This field required a valid url
Current translation: This field required a valid URL

Your question or comment:

url > URL

**Comment by Markionium** [comment]
It should probably also be `requires` instead of `required`
