### ISSUE TITLE
Add support for legend set

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#228]
Add support for CRUD operations for legend set.

**Comment by Markionium** [comment]
Validation feels a bit wonky with the alert box showing up quickly when generating a new legendSet.

Should look into why the validation does not run on a `ModelCollectionProperty`, so we can disable the field.

**Comment by Markionium** [comment]
Clone for `legendSet` currently fails but does not show an error.

**Comment by Markionium** [comment]
Deletion of `legendSet` fails with 500

**Comment by jijukjose** [comment]
https://github.com/dhis2/dhis2-docs/issues/156
