### ISSUE TITLE
Add support for Predictor

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#229]
Add CRUD support for Predictors.

<pre>/api/predictors</pre>

Fields
---
| Field | UI type | Property name | Model type |
| --- | --- | --- | --- |
| Name | Text field | name | String |
| Code | Text field | code | String |
| Description | Text area | description | String |
| Period type | Drop down| periodType | Object |
| Organisation unit levels | Multiple available/selected list | organisationUnitLevels | Object array |
| Generator expression | Indicator style expression dialog | generator | Object |
| Sample skip test expression | Expression - text area for now | sampleSkipTest | Object |
| Sequential sample count | Positive number field | sequentialSampleCount | Integer |
| Annual sample count | Positive number field | annualSampleCount | Integer |
| Sequential sample count | Positive number field | sequentialSkipCount | Integer |

Expression manager (for generator and skipSampleTest fields)
---
- [x] Constant options https://github.com/dhis2/d2-ui/issues/80
- [x] Org unit group options https://github.com/dhis2/d2-ui/issues/80
- [x] Fix validation https://github.com/dhis2/maintenance-app/issues/235

**Comment by jijukjose** [comment]
https://github.com/dhis2/dhis2-docs/issues/200
