### ISSUE TITLE
Search across name, short name, code, uid for objects

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#232]
For the search in object lists, apply the search across display name, display short name (if available), code and UID object properties. Currently only display name is available.

This depends on a new query syntax being available in the API. The syntax will look like this:

<pre>?filter=displayName:ilike:A&filter=code:ilike:A&logicMode=OR</pre>

**Comment by mortenoh** [comment]
The final syntax is not `logicMode=AND/OR` but `rootJunction=AND/OR`, this
has landed in trunk now.

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org
