### ISSUE TITLE
Introduce Push analysis object with CRUD operations

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#237]
Introduce CRUD operations for a new object PushAnalysis.

Base API URL:

<pre>/api/pushAnalysis</pre>

Fields
---
The following fields are needed.

API field | UI Label | Input type
--- | --- | ---
name | Name | Input field
message | Message | Text area
dashboard | Dashboard | Drop down list based on ```/api/dashboards```
recipientUserGroups | Recipients | Available-selected widget based on ```/api/userGroups```
enabled | Enabled | Checkbox - checked on by default

**Comment by nicolayr** [comment]
Fixed in 748a9eb344fde945efd6fc3867efef5cc6b4f28d by @Markionium

**Comment by jijukjose** [comment]
https://github.com/dhis2/dhis2-docs/issues/177
