### ISSUE TITLE
Unable to edit a translation that was just created

### ISSUE THREAD

**Issue by Awnage** [dhis2/maintenance-app#242]
When creating a translation, it is not possible to immediately edit that translation. One needs to close and reopen the dialog. This can then cause the problem described in #241 

**Steps to reproduce:**
1. Create an object (say, Org Unit Group)
2. Open Translate dialog for the object
3. Select any locale
4. Add a Name
5. Hit tab or click somewhere so that the record saves
6. Edit the field you just modified
7. Click elsewhere

Popup says "Could not save the translation. DISMISS". Web console shows 

`HTTP Status 500 - Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [translation_composite_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
`

I surmise this is because it is performing a POST instead of a PUT.

DHIS2 Version: 2.23
Build revision: 22912

**Comment by Markionium** [comment]
This has been fixed in a later version.
