### ISSUE TITLE
Predictors: remove link for manually creating org unit levels

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/maintenance-app#246]
In the "Create new predictor" form, you can click on "Add new organisation unit level":

![addneworgunitlevel](https://cloud.githubusercontent.com/assets/18207911/18749163/df34b386-80d5-11e6-84b1-d848f70b43cf.png)

Then a new tab opens with the following form:

![orgunitleveladdnew](https://cloud.githubusercontent.com/assets/18207911/18749296/814a7b9c-80d6-11e6-8a6b-262c7b4ecb66.png)

The form gives an error when you click "Save".

However, in "Organisation unit level management" screen, there's no "Create new icon":

![orgunitlevelmgmt](https://cloud.githubusercontent.com/assets/18207911/18749299/85fc41b6-80d6-11e6-9fba-828030273af3.png)

Should the user be able to create organisation unit levels? If yes, add "Add new" icon to the "Organisation unit level management" screen. If not, remove the "Add new" icon from the "Create new legend" form.

**Comment by nicolayr** [comment]
Org unit levels are created automatically by the system, so the bug here is that the link to creating new org unit levels exist in the first place ;)

**Comment by Markionium** [comment]
Exactly. I'm not really sure how to cleanly solve it. Perhaps we should have a `showAddButton` boolean prop on the multi-select and async-drop-down fields. That defaults to true, but we use the override to set it to false for organisationUnitLevel on Predictor.

**Comment by nicolayr** [comment]
Since we already have `d2.currentUser.canCreate()`, I used that.

In the process I discovered that there was a create button for org unit levels in the data element form as well - although there it's labelled "aggregation levels".

**Comment by Markionium** [comment]
Right that is probably better :D I bit less flexible but more robust (and we don't really need that flexibility). 

Yes the aggregation levels thing is a bit weird.. probably historical reasons.
