### ISSUE TITLE
Category combo: Category list must be filtered according to data dimension type

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#248]
In the add/edit category combo screen, the "Available categories" list should be filtered by the currently selected "data dimension type". Also, when the data dimension type selected is changed, the "selected category list" must be cleared.

The concept is that a category combo of a specific data dimension type is only allowed to contain categories of the same data dimension type.

**Comment by Markionium** [comment]
![image](https://cloud.githubusercontent.com/assets/2134901/19521900/b04df1c2-9615-11e6-8522-cefae75e0fa9.png)

**Comment by Markionium** [comment]
Backport to 2.24
