### ISSUE TITLE
Add Data Approval Levels and Data Approval Workflows

### ISSUE THREAD

**Issue by nicolayr** [dhis2/maintenance-app#255]
And remove them from the settings app (https://github.com/dhis2/settings-app/issues/84)

**Comment by ceciliapersson** [comment]
I've created a corresponding doc issue:
https://github.com/dhis2/dhis2-docs/issues/410

**Comment by nicolayr** [comment]
I'm not sure this will happen for 2.26, fyi :)

**Comment by ceciliapersson** [comment]
ok, good to know :)
