### ISSUE TITLE
External layers: imageFormat should not be required for XYZ tiles

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#257]
When I try to save my first external layer using the XYZ format, I'm getting a error message when saving: "Missing required property 'imageFromat'. This field is only required for WMS. 

If I change to WMS, select a image format, and then change back to XYZ, I'm allowed to save. 

![screen shot 2016-10-05 at 16 28 02](https://cloud.githubusercontent.com/assets/548708/19117456/581a0024-8b19-11e6-9eeb-ee88ca5337e4.png)

**Comment by nicolayr** [comment]
In that case the schema should be changed as well, since currently `imageFormat` is required for all external map layers (https://play.dhis2.org/dev/api/schemas/externalMapLayer/imageFormat.json)
@vietnguyen - can you have a look at that?

**Comment by turban** [comment]
If it's going to be required, the default value should always be PNG.

**Comment by nicolayr** [comment]
Ok, only needs to be fixed in the maintenance app then.
