### ISSUE TITLE
Not allowed to save legend with negative numbers

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#259]
EditModelForm.component.js:347 Could not save legend (Allowed range for numeric property `endValue` is [0 to 179,...

![screen shot 2016-10-05 at 18 29 47](https://cloud.githubusercontent.com/assets/548708/19122246/da29299a-8b29-11e6-9a25-6c16126e54f4.png)

**Comment by nicolayr** [comment]
This needs to be fixed in the schema, and should then be picked up automatically by the maintenance app:
https://play.dhis2.org/dev/api/schemas/legend/endValue.json

**Comment by turban** [comment]
Who can fix the schema? 

Also reported by Olav Poppe 27 October:

Hi devs,
it looks like it is not possible to have negative numbers for start/end intervals for legends. Tested on 2.24 and 2.25.

- is it correct that it’s not supported?
- if it’s not supported, can I write a blueprint for it?

Concrete need in my case is having a discrete colour for negative dropout rates.
