### ISSUE TITLE
objectActions.js:11 Uncaught TypeError: n.i(...) is not a function

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/maintenance-app#266]
App fails to load with...

objectActions.js:11 Uncaught TypeError: n.i(...) is not a function(anonymous function) @ objectActions.js:11t @ bootstrap a7e0ddd…:52(anonymous function) @ maintenance-a7e0ddd….js:7416t @ bootstrap a7e0ddd…:52(anonymous function) @ maintenance-a7e0ddd….js:14341t @ bootstrap a7e0ddd…:52window.webpackJsonp @ bootstrap a7e0ddd…:23(anonymous function) @ maintenance-a7e0ddd….js:1

Version:
2.25
Build revision:
8a7d3cc

**Comment by Markionium** [comment]
Seems like the fix that corrected that wasn't published correctly. I deployed the corrected version a few days ago.

Re-open if you have any issues.
