### ISSUE TITLE
Remove one category combo per section constraint in dataset section

### ISSUE THREAD

**Issue by abyot** [dhis2/maintenance-app#271]
https://blueprints.launchpad.net/dhis2/+spec/section-remove-single-category-combo

**Comment by troyel** [comment]
I can't find this issue in Jira. @nicolayr  can you confirm that this is still in the pipeline? I see that adding row and column totals have been done but adding sections consisting of different category comboes doesn't seem to work on play yet. We have development pending on this change in NRC. Thanks!

**Comment by nicolayr** [comment]
This is working on play. However the UI is a bit misleading:
The category combo dropdown in the dataset section dialog is only a filter to make it easier to find the data element you're looking for. All data elements you add to the section are saved, even though it _looks_ like only the data elements from the currently selected category combo are assigned.

**Comment by troyel** [comment]
Thanks for the swift feedback. True! Tested and works! Do you know if this is ported to 2.25? I tried checking our 2.25 instance and there the add section button doesn't seem to work/respond at all.

Version:
2.25
Build revision:
430e4fb

**Comment by nicolayr** [comment]
Support for multiple category combos per section was added in 2.26.

It sounds like you might be having an unrelated issue. If so, please report a bug on Jira so we can track it properly.
