### ISSUE TITLE
Data Element aggregation type should not be set to None for all Tracker domain elements

### ISSUE THREAD

**Issue by olatitle** [dhis2/maintenance-app#278]
Data Element Add/edit:
When setting a data element's domain type to "Tracker" the Aggregation type is set to "None" and then blocked for editing.

This causes serious problems in analytics as Event Data Items are uses across all data analysis tools. Event Data Items are aggregate values of numeric (perhaps also boolean?) tracker data elements as many tracker data elements are perfectly fine to aggregate. 

The aggregation type show/hide logic should not depend on the domain type, but rather the value type. Now it seems to depend on both.

Right now analytics actually causes sql grammar exception as the queries generated from a data selection with event data items uses the aggregation type as part of the sql query string, and (None) is not supported in SQL.

**Comment by Markionium** [comment]
@larshelge @abyot Can you have a look at if this is correct?

I don't know why we got this requirement to disable it, but if we are to enable it, for which types exactly would it work/be supported?

**Comment by abyot** [comment]
From the tracker apps perspective, the key is to be able to render an input field corresponding to a given value type. Can't really comment how value types are dealt in aggregation.

Technically speaking, I don't see a reason for not allowing the same aggregation <-> value type logic that we have in aggregate for tracker.

**Comment by Markionium** [comment]
Thanks @abyot. In that case i guess we'll need to wait for @larshelge to respond. :)

**Comment by larshelge** [comment]
Yes just go ahead, no need to bloc aggregation type for tracker data elements.
