### ISSUE TITLE
Indicator numerator editor, data elements do not load

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#32]
Indicator numerator editor, data elements do not load in the list.

https://play.dhis2.org/demo/dhis-web-maintenance/#/edit/indicator/po1QxztD1K1

Check on demo, version 2.22.

![ind](https://cloud.githubusercontent.com/assets/908206/12759760/4b5c7bde-c9e3-11e5-812b-61e9f9b1b32d.png)

**Comment by Markionium** [comment]
Server side timeout issue, therefore closing this here.
