### ISSUE TITLE
Indicator - Decimals in data output - 0 is not stored

### ISSUE THREAD

**Issue by olavpo** [dhis2/maintenance-app#39]
It is not possible to set "Decimals in data output" to 0 when adding/editing an indicator. It is in the dropdown, but it is nulled when you select it and when trying to save it says "no changes".

Reproduced on /demo (2.22)

**Comment by Markionium** [comment]
It seems like the issue is not just related to the `0` value.

The api `/api/indicators/` end point does not seem to return the decimals value, therefore the value always shows as empty. 

Will have to see if this field is now obsolete or it is an error that it is not there by error.

**Comment by Markionium** [comment]
Solved by Morten in API.
