### ISSUE TITLE
Indicator numerator, totals missing on next and previous page

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#51]
In indicator numerator editor, in the list of data elements, the totals for data elements with option combos are not present when going to next and previous page.

Hint: Add &totals=true to the request URL for /dataElementOperands also for next/prev.

**Comment by Markionium** [comment]
Fixed for 2.22 in https://github.com/dhis2/maintenance-app/commit/d82cfa0c0ab7cd5f63a1af95e643baf91b9a40d9
