### ISSUE TITLE
Data elements, icon spinning forever when no aggregation levels

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#53]
In add / edit data elements screen, when there are no aggregation levels, the icon keeps spinning forever.

![attributes](https://cloud.githubusercontent.com/assets/908206/13555605/162c32a0-e3c5-11e5-8c84-b07da0df19a4.png)

**Comment by jason-p-pickering** [comment]
Can confirm that this.  "Fix" is to add orgunits.

**Comment by Markionium** [comment]
We're aware, see https://github.com/dhis2/d2-ui/issues/27

**Comment by nicolayr** [comment]
This _should_ be fixed now, just need to verify.
