### ISSUE TITLE
Assign all button not easily clickable

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#55]
In add/edit data element screen, the "Assign all" button for aggregation levels is not easily clickable. The button does only become clickable when hovering a very small area in the middle, not while hovering outside the text.

![assign](https://cloud.githubusercontent.com/assets/908206/13557554/f81e5ad0-e3f2-11e5-8d42-9b01206c77cf.png)

**Comment by Markionium** [comment]
Minor overlap of DOM elements.
