### ISSUE TITLE
Translate option not available?

### ISSUE THREAD

**Issue by Markionium** [dhis2/maintenance-app#59]
https://lists.launchpad.net/dhis2-users/msg09202.html

**Comment by Markionium** [comment]
Seems like the `translate` property has been removed from the `/api/schemas` endpoint.

**Comment by mortenoh** [comment]
Yes, we do not require this flag anymore as it's updated
automatically internally

On Mon, Mar 14, 2016 at 3:28 PM, Mark Polak <notifications@github.com>
wrote:

> Seems like the translate property has been removed from the /api/schemas
> endpoint.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhis2/maintenance-app/issues/59#issuecomment-196200756>
> .
>



-- 
Morten

**Comment by Markionium** [comment]
I am using it though, so it would be nice to have this back :) 

@see https://bugs.launchpad.net/dhis2/+bug/1556799

**Comment by mortenoh** [comment]
This flag is purely internal.. what did you use it for? it probably should
have never been exposed..

On Mon, Mar 14, 2016 at 3:37 PM, Mark Polak <notifications@github.com>
wrote:

> I am using it though, so it would be nice to have this back :)
>
> @see <https://github.com/see>
> https://bugs.launchpad.net/dhis2/+bug/1556799
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhis2/maintenance-app/issues/59#issuecomment-196203944>
> .
>



-- 
Morten

**Comment by Markionium** [comment]
Basically to determine if an object can be translated. To determine availability of the database translate dialog.

**Comment by mortenoh** [comment]
Oh, but that is not what it means... what is means is just that if any
translations are available for that object.. if you use it like that, you
will see very strange behavior.. all id objects can be translated

On Mon, Mar 14, 2016 at 3:40 PM, Mark Polak <notifications@github.com>
wrote:

> Basically to determine if an object can be translated. To determine
> availability of the database translate dialog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhis2/maintenance-app/issues/59#issuecomment-196204636>
> .
>



-- 
Morten

**Comment by Markionium** [comment]
Right ok, so what is the correct property to use?

If you say all `id` objects can be translated i assume it means i can use `identifiableObject` to determine if an object can be translated?

**Comment by mortenoh** [comment]
Yeah, that should work.. the translation itself happens in a different
table.. so we don't need to extend the id object itself like we do for
attributeValues / ACL

On Mon, Mar 14, 2016 at 3:44 PM, Mark Polak <notifications@github.com>
wrote:

> Right ok, so what is the correct property to use?
>
> If you say all id objects can be translated i assume it means i can use
> identifiableObject to determine if an object can be translated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhis2/maintenance-app/issues/59#issuecomment-196206180>
> .
>



-- 
Morten

**Comment by Markionium** [comment]
Right ok, cool then i'll adjust and backport :) 

Thanks @mortenoh
