### ISSUE TITLE
Window movement during numerator/denominator configuration

### ISSUE THREAD

**Issue by olavpo** [dhis2/maintenance-app#67]
2.22 rev 21923

When defining a numerator and denominator, the window is resized and moves slightly when a data element (operand) is selected and the formula description appears for the first time. 

This means that if you plan on adding two consecutive fields in the list of data elements with the mouse, you will often miss the second because it has moved slightly.

**Comment by olavpo** [comment]
I now realise I was using Safari rather than Chrome. Looks like there are some layout issues with the numerator/denominotor configuration in Safari (e.g. line height in list of data elements is smaller, so there is too much whitespace, not indicator when scrolling etc).

**Comment by Markionium** [comment]
@olavpo For visual stuff could you add screenshots next time? 

Its quite straightforward on mac. Just take the screenshot with `shift` + `crtl` + `cmd` + `4`  and then `cmd` + `v` in the github comment box to upload :)

**Comment by olavpo** [comment]
I actually did a screen capture, but github did not allow me to upload it. Difficult to see the movement in a screenshot, can email it to you.

**Comment by Markionium** [comment]
Perhaps that also only works in chrome ;)

**Comment by Markionium** [comment]
Ah right it's a .mov not a screenshot :D

Thanks for emailing
