### ISSUE TITLE
Category add/edit screen, move category options up and down

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#71]
In add/edit category screen, add functions for moving category options up and down in the selected category option list. It must be possible to rearrange the order of category options.

**Comment by Markionium** [comment]
This can be achieved by submit the order in the modified order in the PUT request when saving.

**Comment by Markionium** [comment]
See https://github.com/dhis2/d2-ui/issues/47

**Comment by Markionium** [comment]
Fixed 1a81625ae40e52f581c195bc34b68bcbb92438d8 and https://github.com/dhis2/d2-ui/commit/5f29837c2a717f491c675346932b580ccc82a51b
