### ISSUE TITLE
Indicator numerator screen > Program lists sorting

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#74]
In Indicator numerator screen, under Programs, all lists (Data elements, Tracked entity attributes, Program indicators) must be sorted alphabetically.

![sorting](https://cloud.githubusercontent.com/assets/908206/13983002/59645072-f0ed-11e5-9e96-25e3d8874c15.png)

**Comment by jason-p-pickering** [comment]
Maybe a corner case, but how is alphabetical sorting of non-Latin scripts (i.e. Arabic and Burmese) handled?
