### ISSUE TITLE
No changes should close edit dialog and take you back to list

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#76]
In edit object screens, when you click Save after making changes you are redirected back to list. If no changes, you are informed and nothing happens. Change behavior so that clicking Save always take you back to the list. Inform the user that no changes took place in the info box.

The reason is that clicking Save normally takes you to the list so that is what users expect and would like to do. We can rather inform the user that no changes took place in the info box afterwards.

**Comment by mortenoh** [comment]
I agree with this. Given that your model supports "dirty", we can just do a
simple redirect, no update required.

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org
