### ISSUE TITLE
Allow un-selecting option set on edit data element

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#77]
In edit data element screen, for the option set and comment option set drop-downs, it must be possible to completely un-select any option set, e.g. select no option set, when the data element currently has an option set.

This applies more generally to non-mandatory fields with drop-downs, in the sense that is should be possible to un-select the current option.

Applies also to data element > legend set.

**Comment by Markionium** [comment]
Fix should be implemented within the latest app. It seems that the api currently has unexpected behaviour when updating these values see bug reports listed below.

https://bugs.launchpad.net/dhis2/+bug/1563546
https://bugs.launchpad.net/dhis2/+bug/1563559

**Comment by larshelge** [comment]
Can we please have this fix back-ported to 2.22? Show-stopper for some organizations for upgrading to 2.22.
