### ISSUE TITLE
Data element value type to be determined by option set

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#78]
In add / edit data element screen, when an option set is selected (not the comment one, just the regular option set), the data element value type should be set to the value type of the option set, and the value type drop-down should be disabled for manual selection.

The reason for this is that the data element value type must match the type of the option codes in the selected option set in order to make sense.

**Comment by Markionium** [comment]
This is a business logic thing that should also be enforced through the API. 

Will implement it as described above however to prevent reduce the possibility to make the mistake.
