### ISSUE TITLE
Checkboxes not checked for boolean dynamic metadata attributes

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#82]
For dynamic metadata attributes of type Yes/No (boolean), checkboxes are not being checked even if the attribute value is true. Applies to category option and likely all other types.

**Comment by Markionium** [comment]
I'm aware, already have a fix in place for this. Should go along with the bigger batch up updates.

However will need to fix it for 2.22 separately.

**Comment by larshelge** [comment]
Credit for screenshot goes to Rodolfo M.

**Comment by rodmelia** [comment]
Hi - we really appreciate if this can make it to 2.22. We use attributes Y/N at PSI, as well as JHPIEGO.

**Comment by Markionium** [comment]
@rodmelia Yes i'll get a fix in place over the weekend.

**Comment by Markionium** [comment]
Fixed in 2.22 through 2e1f6b50c65fcbac235315ebeffc2dd8bca47834

@rodmelia Please verify and see if it works as expected. (If not please re-open)

**Comment by larshelge** [comment]
Still not working in trunk.

**Comment by Markionium** [comment]
It's working in trunk, re-opening to verify for 2.22.

**Comment by Markionium** [comment]
Verified that it works in both latest trunk and 2.22 versions of the app.
