### ISSUE TITLE
Right-click browser context menu must be disabled

### ISSUE THREAD

**Issue by larshelge** [dhis2/maintenance-app#91]
In the lists of objects, right-clicking once gives the context menu, next time it produces the browser native context menu, which is confusing.

![right](https://cloud.githubusercontent.com/assets/908206/14411866/db748a08-ff54-11e5-95e4-7171674a496f.png)

**Comment by Markionium** [comment]
This is currently not trivial to implement as the click on different rows is on an overlay. We could disable it in the context menu itself, but i don't see that as a big issue.

Perhaps right click is not that intuitive and maybe we should just rely on the three dot menu button that was added.
