### ISSUE TITLE
Labels on date fields not clickable

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#97]
For text fields, I can click the label to edit the contents. This does not work for date fields, where I need to hit the line below.

![screen shot 2016-04-13 at 11 25 10](https://cloud.githubusercontent.com/assets/548708/14488929/e35df7f0-016a-11e6-8b12-02c59db77de8.png)

**Comment by Markionium** [comment]
Likely has to do with https://github.com/callemall/material-ui/issues/3908.

**Comment by Markionium** [comment]
This issue does not persist in the latest version of material-ui. It should therefore be fixed by upgrading to the next version.
