### ISSUE TITLE
Which translations exists for an item?

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#99]
Would it be possible to list the available translations that exists (with link to the translation dialog) in the info box?

![screen shot 2016-04-13 at 11 55 10](https://cloud.githubusercontent.com/assets/548708/14489643/aca2e3a2-016e-11e6-9921-a1590a77aa2a.png)

Currently I need to search up the local for each item.

**Comment by turban** [comment]
Existing translations could also show in this dialog: 

![screen shot 2016-04-13 at 12 12 04](https://cloud.githubusercontent.com/assets/548708/14490109/1c092362-0171-11e6-83f1-f959d2d39e2e.png)

**Comment by Markionium** [comment]
I think this might be better solved with a separate translation window. 

The current translation workflow for meta data seems a bit unpractical.
